version: '3'
services:
  fastapi_exam:
    container_name: "mongo_api_exam"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/exam_api
  mongodb_exam:
    container_name: c_mongo_exam
    image: mongo:latest
    ports:
       - "4801:27017"
    depends_on:
       - fastapi_exam
  fill_db:
    container_name: "fill_db"
    build:
      context: .
      dockerfile: seed_mongo.Dockerfile
    ports:
      - "4080:4080"
    depends_on:
      - mongodb_exam
