version: '3'
services:
  fastapi_exam:
    container_name: "mongo_api_exam"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "4800:4800"
    volumes:
      - .:/exam
  mongodb_exam:
    container_name: c_mongo_exam
    image: mongo:latest
    ports:
       - "4801:27017"
    depends_on:
       - fastapi_exam
